[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
PLAYWRIGHT_BROWSERS_PATH = "0"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[dev]
command = "npm run dev"
targetPort = 5173
functionsPort = 8888

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[edge_functions]]
path = "/gallery/*"
function = "gallery-cache"
